# Generated by Django 4.0.1 on 2022-01-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='placeholder')),
                ('mhs', models.FloatField()),
                ('power', models.IntegerField()),
                ('price', models.FloatField()),
                ('kwh_price', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('epp', models.FloatField()),
                ('roi', models.FloatField()),
            ],
        ),
    ]
